### PR TITLE
Zulkhairi test

### PR DESCRIPTION
**Pull request by zulkhairiradzi**
My solution for the interview exercise

### CODE REVIEW

**Comment by rashidi** [comment]
Hello @zulkhairiradzi,

May I know if you have submitted your resume to us or our recruiters?

**Comment by zulkhairiradzi** [comment]
> Hello @zulkhairiradzi,
> 
> May I know if you have submitted your resume to us or our recruiters?

through recruiter

**Comment by rashidi** [comment]
@zulkhairiradzi, may I know which recruiter? The agency or the name.

**Comment by rashidi** [comment]
@zulkhairiradzi, it's okay. I found out. See you soon.

**Pull request closed without merging**
